### PR TITLE
Allow symfony/http-foundation ^5

### PR DESCRIPTION
**Pull request by bramus**
This PR allows `symfony/http-foundation` ^5.0 to be used.

### CODE REVIEW

**Comment by bramus** [comment]
Tests are failing, but that's unrelated to the contents of this PR. Once that PR #4 gets merged, this PR can be brought up-to-date, and tests will pass.

**Comment by IndraGunawan** [comment]
thanks @bramus !

**Comment by bramus** [comment]
You're welcome! Could you tag a new version _(0.0.2 I guess?)_ so that I can lock to it in my code? Thanks!

**Comment by IndraGunawan** [comment]
i already create a release for these changes https://github.com/IndraGunawan/swoole-http-message-bridge/releases/tag/v0.1.0

**Comment by bramus** [comment]
Ah sorry, overlooked the difference between 0.0.1 and 0.1.0 … looks lik I need some more coffee 😅

**Pull request merged**
